List<Map<String, dynamic>> electronicGadgets = [
  {
    'category': 'Smartphone',
    'name': 'iPhone 13 Pro',
    'price': 999.99,
    'image': 'https://pngimg.com/uploads/iphone_13/iphone_13_PNG28.png',
    'rating': 4.5,
    'likesPercentage': 92,
    'numberOfReviews': 1000,
    'sale': '% On sale',
    'description': 'The iPhone 13 Pro features a stunning Super Retina XDR display, advanced A15 Bionic chip, and pro camera system.',
  },
  {
    'category': 'Laptop',
    'name': 'MacBook Pro',
    'price': 1299.99,
    'image': 'https://www.pngarts.com/files/4/Apple-Macbook-Pro-Transparent-Image.png',
    'rating': 4.8,
    'likesPercentage': 95,
    'numberOfReviews': 800,
    'sale': '% On sale',
    'description': 'The MacBook Pro is a powerful laptop with M1 Pro or M1 Max chip, Liquid Retina XDR display, and up to 64GB of memory.',
  },
  {
    'category': 'Smartwatch',
    'name': 'Apple Watch 7',
    'price': 399.99,
    'image': 'https://www.pngarts.com/files/8/Apple-Watch-PNG-Transparent-Image.png',
    'rating': 4.7,
    'likesPercentage': 94,
    'numberOfReviews': 600,
    'sale': '% On sale',
    'description': 'The Apple Watch Series 7 features a larger, always-on display, advanced health tracking, and fast charging.',
  },
  {
    'category': 'Tablet',
    'name': 'iPad Air',
    'price': 599.99,
    'image': 'https://images.frandroid.com/wp-content/uploads/2020/09/apple-ipad-air-2020-frandroid.png',
    'rating': 4.6,
    'likesPercentage': 91,
    'numberOfReviews': 500,
    'sale': '% On sale',
    'description': 'The iPad Air offers a stunning Liquid Retina display, powerful A14 Bionic chip, and support for Apple Pencil and Magic Keyboard.',
  },
  {
    'category': 'Headphones',
    'name': 'Sony WH-10',
    'price': 349.99,
    'image': 'https://www.sony.com/is/image/gwtprod/a623e0ac346dea68e59c279e05221b59?fmt=png-alpha&wid=515&hei=515&trf=trim',
    'rating': 4.9,
    'likesPercentage': 98,
    'numberOfReviews': 1200,
    'sale': '% On sale',
    'description': 'The Sony WH-1000XM4 headphones deliver industry-leading noise cancellation, premium sound quality, and long battery life.',
  },

];
