List<Map<String, dynamic>> electronicGadgets = [
  {
    'category': 'Smartphone',
    'name': 'iPhone 13 Pro',
    'price': 999.99,
    'image': 'assets/iphone_13_pro.jpg',
    'rating': 4.5,
    'likesPercentage': 92,
    'numberOfReviews': 1000,
    'description': 'The iPhone 13 Pro features a stunning Super Retina XDR display, advanced A15 Bionic chip, and pro camera system.',
  },
  {
    'category': 'Laptop',
    'name': 'MacBook Pro',
    'price': 1299.99,
    'image': 'assets/macbook_pro.jpg',
    'rating': 4.8,
    'likesPercentage': 95,
    'numberOfReviews': 800,
    'description': 'The MacBook Pro is a powerful laptop with M1 Pro or M1 Max chip, Liquid Retina XDR display, and up to 64GB of memory.',
  },
  {
    'category': 'Smartwatch',
    'name': 'Apple Watch Series 7',
    'price': 399.99,
    'image': 'assets/apple_watch_series_7.jpg',
    'rating': 4.7,
    'likesPercentage': 94,
    'numberOfReviews': 600,
    'description': 'The Apple Watch Series 7 features a larger, always-on display, advanced health tracking, and fast charging.',
  },
  {
    'category': 'Tablet',
    'name': 'iPad Air',
    'price': 599.99,
    'image': 'assets/ipad_air.jpg',
    'rating': 4.6,
    'likesPercentage': 91,
    'numberOfReviews': 500,
    'description': 'The iPad Air offers a stunning Liquid Retina display, powerful A14 Bionic chip, and support for Apple Pencil and Magic Keyboard.',
  },
  {
    'category': 'Headphones',
    'name': 'Sony WH-1000XM4',
    'price': 349.99,
    'image': 'assets/sony_wh_1000xm4.jpg',
    'rating': 4.9,
    'likesPercentage': 98,
    'numberOfReviews': 1200,
    'description': 'The Sony WH-1000XM4 headphones deliver industry-leading noise cancellation, premium sound quality, and long battery life.',
  },

];
