List<Map<String, dynamic>> electronicGadgets = [
  {
    'category': 'Smartphone',
    'name': 'iPhone 13 Pro',
    'price': 39499.99,
    'image': 'https://pngimg.com/uploads/iphone_13/iphone_13_PNG28.png',
    'rating': 4.5,
    'likesPercentage': 92,
    'numberOfReviews': 1000,
    'sale': '% On sale',
    'description': 'The iPhone 13 Pro boasts a stunning display, advanced chip, and pro camera system. With its sleek design and durable construction, itsa stylish and reliable companion for everyday use, offering exceptional performance and photography capabilities',
  },
  {
    'category': 'Laptop',
    'name': 'MacBook Pro',
    'price': 81299.99,
    'image': 'https://www.pngarts.com/files/4/Apple-Macbook-Pro-Transparent-Image.png',
    'rating': 4.8,
    'likesPercentage': 95,
    'numberOfReviews': 800,
    'sale': '% On sale',
    'description': 'The MacBook Pro, powered by the M1 chip, delivers unmatched performance for professional tasks. Its vibrant display and sleek design make it the ultimate tool for productivity on the go, perfect for editing videos, coding, or designing graphics',
  },
  {
    'category': 'Smartwatch',
    'name': 'Apple Watch 7',
    'price': 12399.99,
    'image': 'https://www.pngarts.com/files/8/Apple-Watch-PNG-Transparent-Image.png',
    'rating': 4.7,
    'likesPercentage': 94,
    'numberOfReviews': 600,
    'sale': '% On sale',
    'description': 'The Apple Watch Series 7 features advanced health tracking and all-day battery life. Its sleek design and intuitive interface make it a stylish and practical accessory for modern living, helping you stay on top of your fitness goals and daily tasks',
  },
  {
    'category': 'Tablet',
    'name': 'iPad Air',
    'price': 34599.99,
    'image': 'https://images.frandroid.com/wp-content/uploads/2020/09/apple-ipad-air-2020-frandroid.png',
    'rating': 4.6,
    'likesPercentage': 91,
    'numberOfReviews': 500,
    'sale': '% On sale',
    'description': 'The iPad Air combines powerful performance with portability, featuring a stunning display and support for the Apple Pencil and Magic Keyboard. Its sleek design, lightweight construction, and all-day battery life make it ideal for work, play, and everything in between',
  },
  {
    'category': 'Headphones',
    'name': 'Sony WH-10',
    'price': 15349.99,
    'image': 'https://www.sony.com/is/image/gwtprod/a623e0ac346dea68e59c279e05221b59?fmt=png-alpha&wid=515&hei=515&trf=trim',
    'rating': 4.9,
    'likesPercentage': 98,
    'numberOfReviews': 1200,
    'sale': '% On sale',
    'description': 'The Sony WH-1000XM4 headphones offer industry-leading noise cancellation and premium sound quality. With intuitive controls and smart features, they adapt to your environment seamlessly, delivering crystal-clear audio and all-day comfort, perfect for commuting, working, or relaxing',
  },

];
